### PR TITLE
client backend completed + styling of templates fixed

### PR DESCRIPTION
**Pull request by saurabhranjan1806**

### CODE REVIEW

**Comment by HargovindArora** [comment]
@MakChan Can you please resolve the conflicts? Let me know if there is some issue!

**Comment by saurabhranjan1806** [comment]
travis check is failing, before pushing on github run tests on local system and check if something is wrong.

**Comment by HargovindArora** [comment]
@saurabhranjan1806 The code is fine. The tests are failing due to the new media folder address. I think we should ignore it. Please check.

**Comment by saurabhranjan1806** [comment]
no, we cant ignore tests, it will show build failing in the status. fix that.

**Comment by HargovindArora** [comment]
@codehimanshu  can't we reconfigure the Travis?

**Comment by singhsterabhi** [comment]
The Travis check is failing giving this error
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'

I think this is happening because of this migration right here
https://github.com/GDG-JSS-NOIDA/website/blob/f8c286a460452256ee0067c6d67524228edf447a/register/migrations/0002_register_eventid.py#L21

The default to the ForeignKey is set as django.utils.timezone.now
Either delete the default value from the migration. 
Or add a default value to this right here as the pk of Event and run migrations again. 

https://github.com/GDG-JSS-NOIDA/website/blob/f8c286a460452256ee0067c6d67524228edf447a/register/models.py#L6
That must resolve the issue.

**Pull request merged**
